services:
  leadly_redis:
    container_name: leadly_redis
    image: redis:alpine
    network_mode: host
    restart: always
    command: redis-server --port 6381 --save 60 1 --loglevel warning
    volumes:
      - leadly_redis_data:/data

  leadly_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: host
    container_name: leadly_backend
    restart: always
    pull_policy: never
    env_file: "./backend/.env"
    depends_on:
      - leadly_redis

  leadly_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ["bun", "src/workers/reddit.worker.ts"]
    container_name: leadly_worker
    network_mode: host
    restart: always
    pull_policy: never
    env_file: "./backend/.env"
    depends_on:
      - leadly_backend
      - leadly_redis

  leadly_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: "./frontend/.env"
    network_mode: host
    container_name: leadly_frontend
    restart: always
    pull_policy: never
    depends_on:
      - leadly_backend

volumes:
  leadly_redis_data:

networks:
  default: 
    external: true
    name: host
