services:
  leadly_redis:
    container_name: leadly_redis
    image: redis:7-alpine
    network_mode: host
    restart: always
    pull_policy: if_not_present
    command: redis-server --port 6381 --save 60 1 --loglevel warning
    volumes:
      - leadly_redis_data:/data

  leadly_db:
    image: postgres:15-alpine
    container_name: leadly_db
    network_mode: host
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - leadly_postgres_data:/var/lib/postgresql/data
    
    command: >
      postgres 
      -p 5433
      -c listen_addresses='localhost'
      -c max_connections=20
      -c shared_buffers=1GB 
      -c effective_cache_size=3GB 
      -c maintenance_work_mem=64MB 
      -c checkpoint_completion_target=0.9 
      -c wal_buffers=16MB 
      -c default_statistics_target=100 
      -c random_page_cost=1.1 
      -c effective_io_concurrency=200

  leadly_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: host
    image: leadly_backend:${TAG}
    container_name: leadly_backend
    restart: always
    pull_policy: build
    environment:
      - PORT=${BACKEND_PORT}
      - DATABASE_URL
      - NODE_ENV
      - SESSION_SECRET
      - FRONTEND_URL
      - NITTER_URL=
      - REDIS_URL
      - DODO_API_KEY
      - DODO_ENVIRONMENT
      - DODO_WEBHOOK_SECRET
      - DODO_PRO_PRODUCT_ID
      - DODO_PREMIUM_PRODUCT_ID
      - REDDIT_CLIENT_ID
      - REDDIT_CLIENT_SECRET
      - REDDIT_USERNAME
      - GOOGLE_GENERATIVE_AI_API_KEY
    depends_on:
      - leadly_redis

  leadly_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ["bun", "src/workers/reddit.worker.ts"]
    container_name: leadly_worker
    image: leadly_worker:${TAG}
    network_mode: host
    restart: always
    pull_policy: build
    environment:
      - DATABASE_URL
      - NODE_ENV
      - SESSION_SECRET
      - FRONTEND_URL
      - NITTER_URL=
      - REDIS_URL
      - DODO_API_KEY
      - DODO_ENVIRONMENT
      - DODO_WEBHOOK_SECRET
      - DODO_PRO_PRODUCT_ID
      - DODO_PREMIUM_PRODUCT_ID
      - REDDIT_CLIENT_ID
      - REDDIT_CLIENT_SECRET
      - REDDIT_USERNAME
      - GOOGLE_GENERATIVE_AI_API_KEY
    depends_on:
      - leadly_backend
      - leadly_redis

  leadly_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    network_mode: host
    image: leadly_frontend:${TAG}
    container_name: leadly_frontend
    restart: always
    pull_policy: build
    environment:
      - BACKEND_URL
      - NEXT_PUBLIC_BACKEND_URL
      - PORT=${FRONTEND_PORT}
    depends_on:
      - leadly_backend

  leadly_db_viewer:
    image: adminer
    container_name: leadly_db_viewer
    network_mode: host
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=localhost:5433
    command: php -S 0.0.0.0:8888 -t /var/www/html
    depends_on:
      - leadly_db

  leadly_backup:
    image: prodrigestivill/postgres-backup-local
    container_name: leadly_backup
    network_mode: host
    restart: always
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - SCHEDULE
      - BACKUP_KEEP_DAYS
      - HEALTHCHECK_PORT
      - BACKUP_CHANNEL_ID
      - BACKUP_BOT_TOKEN
      - POST_BACKUP_COMMAND=curl -F chat_id=$${BACKUP_CHANNEL_ID} -F caption="📦 Leadly DB Backup | 📅 $(date "+%Y-%m-%d %H:%M") | 📂 $(basename $$BACKUP_FILE)" -F document=@$$BACKUP_FILE https://api.telegram.org/bot$${BACKUP_BOT_TOKEN}/sendDocument

    volumes:
      - leadly_backup_data:/backups
    depends_on:
      - leadly_db

volumes:
  leadly_redis_data:
  leadly_postgres_data:
  leadly_backup_data:

networks:
  default: 
    external: true
    name: host
